# fly.toml file generated for engagement-core on 2022-08-28T02:58:08+08:00

app = "engagement-core"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "kehvinbehvin/engagement-tracker:latest"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
